### ISSUE TITLE
Singularity container can't be run in snakemake pipelines

### ISSUE THREAD

**Issue by leoisl** [iqbal-lab-org/make_prg#20]
I tried to run the [make_prg singularity container (latest)](https://github.com/rmcolq/make_prg#singularity) in a `snakemake` pipeline, but got an issue. `snakemake` run the container as (we necessarily need `bash`):

```
Command ' singularity exec --home <suppressed> bash -c 'set -euo pipefail;  python /home/leandro/git/myforks/pandora_analysis_pipeline/.snakemake/scripts/tmp_b7uof0h.run_make_prg.py'' returned non-zero exit status 255.
```

Error is:
```
FATAL:   "bash": executable file not found in $PATH
```

Upon further inspection of the container, indeed `bash` not only cannot be found in `$PATH`, but it is not installed at all, which seems weird to me, as this line: https://github.com/rmcolq/make_prg/blob/c00fc137456aa474f2f75dd23e1f10c08876dfe9/Singularity#L12 seems to install it

**Comment by mbhall88** [comment]
Oh, I don't think I had updated the latest tag to the actual latest container.

`"library://mbhall88/default/make_prg:0bb4a27"` is actually the latest and has `bash` installed. Although this is **not** the tip of `master`. I have not been updating the container inline with the github repo as I am using a fixed commit.

Ultimately, we should have this set to build a docker container and push to quay.io on pushing a tag to github.
