### ISSUE TITLE
MAFFT is portable for linux and we can embed it into make_prg

### ISSUE THREAD

**Issue by leoisl** [iqbal-lab-org/make_prg#50]
See https://mafft.cbrc.jp/alignment/software/linuxportable.html

Like this, `make_prg` dependencies are all `python` deps, and there is no need to install `mafft` anymore

**Comment by mbhall88** [comment]
Just wondering how necessary this is? If people use the conda package or container then they don't need to worry about mafft anyway. 

Not saying don't do it; just saying it seems low priority to me?

**Comment by leoisl** [comment]
That's true, should have thought about this before finishing the core code yesterday... Is useful just for the pip and binary users. I think conda is the most used manager by bionformaticians, but if they don't use conda, will likely fall back to pip or the binary. I might be wrong, but I have a feeling that container users are just a small fraction

**Comment by leoisl** [comment]
`mafft` is required in `PATH` to run integration tests, and this was sth that bothered me... so might be worth it to do this...

**Comment by leoisl** [comment]
Closed via https://github.com/iqbal-lab-org/make_prg/pull/52
